dimdenGD/OldTwitter

_locales/ru/messages.json
Tbh I kinda love this variant and fine with it, but nobody really commonly use it nowadays in russian language lexicon (not counting literature works, yummy yummy words).
=> More accurate translation for word "born" in ru localization

.github/workflows/pack.yml
This makes it so that for every commit to master, it automatically packs and uploads the extension as an Artifact.
=> Automatic packing with GitHub Actions

layouts/profile/script.js
very bad timing for a bug like that to be found but heres a pr that fixes it to make it quick
i just added a check to see if the private users profile that you're viewing is you (and rearranged some code to make that work)
=> fix #213 (private accounts cannot view themselves)

_locales/en/messages.json, _locales/ko/messages.json, _locales/ru/messages.json, _locales/uk/messages.json, layouts/header/script.js, layouts/header/style.css, layouts/home/index.html, layouts/home/script.js, layouts/home/style.css, layouts/profile/script.js, layouts/profile/style.css
* Fix new tweet input width issue at home page
* Fix reply width does not match with width of thread weet
* Fix trend showing when unblock protected account
* Improve logout modal
* Make Timeline option box go to center when window width is narrow
=> UI Improvement

scripts/apis.js
Note: This won't fix stripped long tweets retweets in home timeline since it doesn't provide `note_tweet`
=> Fix for stripped long tweets in retweets

layouts/bookmarks/style.css, layouts/header/script.js, layouts/header/style.css, layouts/history/style.css, layouts/home/style.css, layouts/itl/style.css, layouts/lists/style.css, layouts/notifications/style.css, layouts/profile/style.css, layouts/search/style.css, layouts/settings/style.css, layouts/topics/style.css, layouts/tweet/style.css, layouts/unfollows/style.css, scripts/apis.js, scripts/helpers.js, scripts/tweetviewer.js
Reverts dimdenGD/OldTwitter#256
=> Revert "Draft: Tweet rendering refactor"

scripts/helpers.js
=> fix for tweets without entities (algo timeline)

_locales/fr/messages.json
=> Update FRENCH messages.json

layouts/header/script.js
couldnt reproduce the issue, but i made an educated guess message_data isnt there in some cases and made it check for message_data lol
=> fix problem with #296

layouts/bookmarks/style.css, layouts/header/style.css, layouts/history/style.css, layouts/home/index.html, layouts/home/script.js, layouts/home/style.css, layouts/itl/style.css, layouts/lists/style.css, layouts/notifications/style.css, layouts/profile/style.css, layouts/search/style.css, layouts/settings/style.css, layouts/topics/style.css, layouts/tweet/style.css, layouts/unfollows/style.css
* Unify width that each page has a little different width elment
* Improve Mobile UI for profile and navi bar
I don't know how to see topic and itl and history page. So I didn't fix them.
=> Improve CSS

scripts/helpers.js
this is my fault, fixing my previous pr #375
i just restored part of the code to how it was before, because i had misread two parts of code as the same thing and merged them into one
=> fix tweet viewing not working occasionally and hashtags showing out of qrts

_locales/zh_CN/messages.json, layouts/header/script.js, layouts/profile/script.js, scripts/injection.js
- The new show-hide action of `#nav-profile-info` will be triggered in PC layout, I wonder if it's a bug so I add a width check.
- Add a check for 🔍 button in mobile layout to prevent searching when there're words in search input box but the box is collapsed, then tapping 🔍 will do the searching instead of expanding the search box.
- update zh_CN translation
=> Mobile layout improve and translation update

README.md, scripts/injection.js
sorry for bothering u with another PR, just wanted to make sure my name was correct before a new release comes out :)
(i only go by Francesco, Rosi is my surname)
=> Updated translator names (only mine lol)

_locales/en/messages.json, layouts/header/script.js, layouts/settings/index.html, layouts/settings/script.js, scripts/config.js
Add disableFindHotKey checkbox.
=> Add disableFindHotKey checkbox

_locales/es/messages.json
update to the spanish translation, 
thx for creating this amazing extension!
my twitter is: @itroeix :D
=> Update Spanish Translation

_locales/en/messages.json, _locales/ru/messages.json, _locales/uk/messages.json, _locales/zh_CN/messages.json, _locales/zh_TW/messages.json, layouts/settings/script.js
Optimized the display of ``<CUSTOM FONT>`` by change the label.
=> optimize <CUSTOM FONT> display

scripts/injection.js
=> Fix #564 #574

scripts/helpers.js
Switch to use youtube-nocookie for YouTube video embeds.
=> use youtube-nocookie for YT embeds

_locales/en/messages.json, scripts/apis.js
Twitter recently pushed an update which fixed the slightly rare "Only on Twitter" text, this will revert it
=> Fix "Only on X" tag

_locales/en/messages.json, layouts/header/script.js, layouts/header/style.css
this is a LOT of stuff so i'll just list changes:
can now handle most message types (including leaving group, changing group icon, etc)
no longer ignores some dms (side effect of above change)
fixed all reaction types (including legacy ones before custom emojis, and new custom ones)
localization for all of this (and localization for message reactions, which wasnt there previously)
and a lot of other small changes/fixes
i've tested this for over a month (out of laziness to finish it and submit a pr), and it works fine
=> dm overhaul

_locales/en/messages.json, scripts/helpers.js
i mean the title says it all...
tested it with notification modal and without notification modal
=> implement #474 (twitter anniversary tweet) and change "X" to "Twitter" in "see less often" message

layouts/bookmarks/style.css, layouts/header/script.js, scripts/apis.js, scripts/helpers.js
unsupported notifications now fallback to external url embedded in all notifications
fixed accounts with no notifications taking forever to load notifications page
fixed style inconsistency in bookmarks page (white border on user pfp instead of --background-color)
fixed harmless dm error (just an error logged, but didnt cause any issues)
and changed vars to lets in anniversary tweet code...
=> small fixes of bugs that slightly annoyed me

layouts/header/script.js
if you previously sent a message to a group dm, the inbox wouldn't load
i have NO idea how i haven't caught this (but to be fair i don't dm a lot)
=> fix dm error

layouts/tweet/script.js, scripts/tweetviewer.js
=> add [follows you] label when viewing tweets' RTs

_locales/nb/messages.json
sorry i thought i fixed this one, won't happen again i hope :(
=> fixed another spelling error

scripts/apis.js
Blue Blocker requires auth headers to be sent..
=> fix: emit headers in sendRequestToEventListeners

README.md
Also gives info on Firefox ESR and Nightly working
=> Add link to Firefox Developer Edition and change name to real one

README.md, _locales/ko/messages.json
Corrected a wrong korean translation in settings panel.
=> correct a wrong korean translation

scripts/background_v2.js, scripts/twchallenge.js
firefox versions relying on gecko versions older than 110 would be served the client-web-legacy version of twitter (basically same thing but compiled with es5 i think)
the problem is that this would completely break request signing, since oldtwitter would try to request the client-web version of the challenge script, as well as that i couldnt get the client-web-legacy version of the challenge script to work properly
so the solution i came to is to detect pre-110 gecko, and then spoof the version to 110 so that twitter would send client-web instead
i also implemented a few extra things into twchallenge (namely a solve queue before the solver is ready), since this was causing hanging problems (no idea why)
as well as not going through with requests when the solver fails, this should …
=> fix oldtwitter on old-ish firefox versions

_locales/ca/messages.json
The "View all" text is translated here
=> Update messages.json for the Catalan translation

_locales/en/messages.json, layouts/header/script.js, layouts/profile/script.js
my changes add a new "user does not exist" page. i have only updated the english localisation as its the only language i speak (sorry). here's a screenshot:3
=> feat: improve "this user does not exist" page

layouts/header/style.css, layouts/profile/style.css, scripts/helpers.js, scripts/injection.js
this pr (albeit hackily) fixes the annoying jump that occurs when you open a modal. haven't been able to test on firefox (i can't get the extension to install) but it should work
=> fix: layout jump on modal open

_locales/tr/messages.json
- Translate the word `font`, as it doesn't exist in Turkish.
- Translate two words that were left in English form
=> translate some untranslated Turkish text

_locales/id/messages.json
also reorganized the lines to match with en, dear god i have a headache seeing it
=> update id locales

README.md, scripts/injection.js
=> Update my contact information & name

_locales/fr/messages.json
=> Updated french (fr) translations

_locales/id/messages.json
Moved nonexist/suspended account description and added two new lines to match with main locale.
=> Update Indonesian (id) translation

README.md, scripts/injection.js
I forgot to add when making the previous pull request :(
=> Add Catalan Translate Credits

_locales/he/messages.json
Hopefully this might be helpful!
=> Update messages.json — Added 3 lines to the Hebrew Localization

_locales/en/messages.json, layouts/header/style.css, scripts/helpers.js
Last year I created issue #744. I have solved it for my personal use, here is my solution in case you want to implement it 😊
=> Highlight which users are blocked in following/followers list

layouts/lists/script.js, layouts/profile/script.js, scripts/helpers.js
just adds the necessary `data-testid`s and elements to make it work without having to use newtwitter
only works in extension compatibility mode obviously
=> sky follower bridge compatibility

_locales/zh_CN/messages.json
* update translation
* delete older duplicate strings
=> Update zh_CN translation

_locales/es/messages.json
- Adds missing translation `always_show_link_color` and `use_retweeted_id`.
- Translates `slow_show_colors_in_timeline` which was in English.
=> Update es translation

README.md, layouts/header/script.js
Other options of this dropdown have hotkeys except blocking, thought it could have one too.
=> Add hotkey to block active tweet's author
