layouts/header/script.js

(this is my first pull request ever so sorry for like, anything?)
group dms sometimes wouldn't load
the reason this happened is because API.getConversation only returned users that had messaged recently, and not ones that reacted recently because oldtwitter doesnt send the "support_reactions=1" query parameter in the conversation api (if it did, then reactions wouldnt show up whatsoever, since they are regularly unsupported in oldtwitter)
so, to fix it, i made it so that every time you open a dm, it checks if there are any missing users, then it adds them to a list of missing users, and then uses API.lookupUsers to all of the missing users' info (in batch of course, not each user separately), then renders conversation as normal

fix group dms not working sometimes

---

scripts/helpers.js
scripts/tweetviewer.js

this is a fix for #146
when you would open a tweet/reply/quote (/status/* pages), if the user had put mentions at the beginning of the tweet, they would be cut off by oldtwitter (to fix the issue of replies showing the users they are replying to at the beginning of the text, which is presumably there for older clients)
to fix this, i split the tweet text with Array.from() (.split splits emojis by bytes, so that breaks things), then slice it using the tweet.display_text_range array that the api sends (this is what i think normal twitter clients do?), then join it back to a string, and that cuts off those fake mentions (since thats what tweet.display_text_range is partly for)

fix mentions at the start of tweets not appearing

---

layouts/notifications/script.js
scripts/helpers.js

this is a fix for #33
when you would have a notification from someone with an emoji (particularly flag emojis and another modifiers), the link would be placed incorrectly, depending on how many emojis and what kind of emojis
to fix it, i split the notification header with Array.from() (again, .split() splits strings by bytes, Array.from() splits by characters i think), then insert the anchor tag wherever its supposed to go, then join it back to a string
i tested it with a test account and a case very similar to the one in the original issue, and it fixes the problem, and causes no other issues

fix emojis breaking profile links in notifications

---

layouts/header/script.js

i have no idea if this was intended or just an "ill do it later" type of thing, but every group dm had its name as a list of all participants and a default icon, which is kind of hard to deal with if ur in multiple group dms
so, i added group dm names and icons, and used the old system as a fallback for group dms which actually have no names or icons, and i also fixed dm text previews saying "dmservice_reaction_one_to_one_media" which would happen because it only checked for "dmservice_reaction_one_to_one_text"

fix(?) group dms not having icons and names

---

layouts/profile/script.js
scripts/helpers.js
scripts/tweetviewer.js

this seems like an unneeded change, and it mostly is, so i dont mind if this pr is denied or whatever
the original code would remove all links and mentions from the tweet text, then ask chrome.i18n.detectLanguage what language it was, then follow through with it if it claimed it were accurate
my code removes all links, mentions, emojis (this one happened more than youd think), and numbers, then asks chrome.i18n.detectLanguage what language it is, and if it couldn't figure it out at all then it would just go with what twitter claimed the tweet language was, and otherwise if it claims it is accurate then it follows through with it like before
this isn't THAT much better (mainly fixes issues with emojis by themselves being detected), but i find it to function better than twitters original …

rewrite tweet language detection

---

layouts/header/style.css

`donate-button` text in Japanese breaks to wrap which collides with lower `about-links` as there is no vertical gap. Changed `word-break` style on `donate-button` to prevent the text breaking. This CSS change should only affect Chinese, Japanese and Korean characters.
`word-break` could be changed on all `about-links a` to prevent mid-word breaking and make it look nicer, but I don't know how that will affect Chinese or Korean, so I haven't made that change.

Change donate button css to prevent collision on (C)J(K) languages

---

scripts/helpers.js
scripts/tweetviewer.js

this is a real twitter bug, not oldtwitter
i have no idea how else to describe it so heres a before and after:
newtwitter:
oldtwitter (fix):
to fix it, i just check if it includes the quote tweet data in the tweet data, if it doesnt, it still usually returns the quote tweet's id, so i get the tweet data with the id instead

fix being unable to see quoted tweets from users who blocked the author

---

scripts/helpers.js
scripts/tweetviewer.js

this was caused by my pr (#209)
to fix it i basically just made it only work on main tweets (like /status/ pages and when you click a tweet on the tl) which is basically what the normal twitter client does, and also checked for t.quoted_status_result which can have the quote tweet data in certain circumstances
the reason i couldnt check if the user was blocking them is because when you fetch a tweet, it doesn't tell you that for some ungodly reason, and t.quoted_status_result is only there if you're blocking the user and the user isn't blocking the author (why?)

sort of fix #218 (my fault)

---

layouts/tweet/script.js
scripts/helpers.js
scripts/tweetviewer.js

the old endpoint just returns a 403 now, so i just replaced all instances of getTweet (wasnt sure if i should just remove API.getTweet altogether, so i kept it for now)
this also fixes being unable to see users who liked and retweeted a tweet

replace all .getTweets with .tweetDetail (old endpoint broke)

---

layouts/header/script.js

The empty "followers" slots look goofy imo so I just made it so they get removed completely.
before (user-followers-div)
after (user-followers-div)
---
before (profile-stat-followers-link)
after (profile-stat-followers-link)

Remove followers texts completely

---

layouts/header/script.js

it used to say the first person in the group dm no matter who reacted to a message, so if the first person was named "first" and the second person reacted, it'd still say first reacted
now it gets the specific user from messageUsers and uses that users name instead

fixed "user reacted to message" subtitle in group dms

---

scripts/apis.js
scripts/helpers.js
scripts/tweetviewer.js

this pr adds rich text support for twitter blue tweets, fixes poll options sometimes showing out of order, fixes quote tweets being treated as the tweet they quoted (i have no idea how else to describe it), and fixes some random overcomplications
rich text is just treated as an entity by parseNoteTweet (rich text works on non note tweets btw), then renderTweetBodyHTML parses the richtext "entity" with b and i html tags (just like it parses links but with bold tags and italic tags, basically)
to fix poll options, instead of taking the i from the loop for the arbitrary choice keys (for some reason, this sometimes ends up out of order?), it just takes only the number from the key and uses that as the "id"
parseNoteTweet now takes t as input instead (because its harder to add new stuff with …

add twitter blue rich text support (and fix a few things)

---

layouts/header/script.js
scripts/apis.js

on [this](https://twitter.com/DavidBaszucki/status/697823530373685248) tweet, it'd error because the tweet being replied to is unavailable and the tombstone handler didnt handle it properly for whatever reason, so i just inspected it and fixed
every time you'd open a dm, every 10 seconds it tries to update the displayed timestamps, but the "data-timestamp" attribute was set incorrectly, so it didnt work. i just used setAttribute instead of setting it on the object, since thats what you're supposed to do anyways
if you click load more over and over in dms, eventually itll loop over to the beginning again, i just made it so if theres no conversations left, it just acts like theres none, and made the cursor for the next page the max_entry_id for the last one so that nothing would load after …

fix a few bugs that annoyed me (tombstone bug, dm errors, and dm "load more" loop)

---

layouts/header/script.js
scripts/apis.js

this pr adds `include_conversation_info=true` to the dm converastion endpoint, and removes the code i added in #182 because it is redundant compared to the flag. this fixes suspended accounts breaking dms, and also fixes the original problem in a more efficient way. i have no idea why or how i didn't find this the first time lol

fix suspended accounts breaking dms (and better fix for my #182)

---

.gitignore
pack.js

Hi, recently I've developed an interest in this project and would like to try poking around & fixing some bugs. I prefer the usability of the Yarn package manager however I ran into problems exporting the extension with Yarn as only NPM is supported. I have forked the extension and changed just two things so Yarn users are also able to work on this extension and build it.

Add yarn package manager compatibility

---

layouts/header/script.js

fixes reading direct messages not working if the last event was a reaction by using the `sort_event_id` instead of the `max_entry_id` for the `last_read_event_id` (newtwitter does this as well)
fixes dming yourself showing a group icon with no name, if you dm yourself then twitter counts the dm as having no messageUsers in it at all, which made oldtwitter assume it was a group since it didnt have exactly ONE messageUser (this also made the code for this more readable)
fixes searching users in any scenario (header search bar, dm search, @ search in tweet) not following the `vars.useOldDefaultProfileImage` setting, the api doesnt return a `default_profile_image` value, so instead it now checks if `profile_image_url_https` includes `default_profile_images`, which is reliable in that case …

fix a few direct message problems (and a search one)

---

_locales/pt_BR/messages.json

This PR should fix errors like this:

Fix translations not using placeholders

---

_locales/uk/messages.json

- виправлено "із-за помилок" на "через помилки"
- виправлено "сповіщені" на "сповіщення"
- заміна "не змогли бути показані" на "не вдалося показати"

fixed grammatical error in ukrainian translation

---

scripts/helpers.js

apparently, twitter sends you the anniversary notification the DAY you joined, not at the exact time, so my original code would result in it being a year behind if you clicked it as soon as you got it

fix issue with anniversary tweets (oops)

---

scripts/helpers.js
scripts/tweetviewer.js

There were some issues with tweet click event handling previously, so I fixed them. For user experience, this effectively means that:
- Clicking on the text of the tweet (or other "deadzones") will now properly open that tweet.
I added two helper functions for determining relationship to a parent. Additionally, I added two extra classes:
- `tweet-button`, which denotes a button behaviour for clickable elements that should not open the tweet. This includes all of the buttons at the bottom of the tweet, as well as the translate button.
- `tweet-edit-section`, for the reply and quote editors, which should also not be interactable.
This solves issue #588.

Improved tweet click event handling.

---

layouts/header/style.css

Since the intended behaviour is to make tweets not open when the cursor is over the text, I thought it would be more obvious if hovering the body text of a tweet changed the cursor to the text selection one.

Use text selection cursor on tweet text.

---

scripts/helpers.js

before if you voted on a poll, due to recent changes, it'd click through the poll option and open the tweet as well
to fix that i just gave poll choices the tweet-button class
and if a poll choice had 0 votes, it's css width would be NaN, so i fixed that too by just falling back to 0 if its not a number

fix voting on polls clicking opening tweets + NaN css width vote count percentage bug

---

scripts/apis.js

on newtwitter, profile media tab was redesigned to be a grid of photos instead of a list of tweets with photos/videos but the api endpoint still returns full tweets, just in a different place so i rewrote the existing code to deal with that and now it works just like it did before
my code checks if the client requests the endpoint with a cursor, if it does then it looks for tweets in `TimelineAddToModule`, otherwise it looks for tweets in `TimelineAddEntries` (why is it like this)
tested on several profiles and it works fine (feels faster if anything lol)

fix photos/videos tab on profiles

---

scripts/apis.js

now just defaults to an empty array if it cant find profile-grid-0 instead of throwing an error

fix media tab of accounts with no media

---

_locales/pt_BR/messages.json

Fixing replace post to tweet function to not conflict with portuguese words. Words like "reply" ("Resposta" in portuguese) contain "post" inside it and turn into ("Restweeta") which is not a word at all.
Inserted a prerequisite to have a " " before the word post for it to be replaced. But there should be a way to change the color of a word when it is replaced, because it does conflict with other words. If someone is posting something at the mail, and tweets about it, it would translate to them tweeting somethng at the mail... The function is useful but a change of color would be useful to avoid misinterpretations.
Same changes apply to replace repost>retweet

Update messages.json (fixing replacement post>tweet function in the PT-BR language)

---

scripts/background_v2.js
scripts/helpers.js
scripts/twchallenge.js

fixes #850 (follow notifications open newtwitter) by adding support for "follow_from_recommended_user" element keyword thing
refines firefox fix
the original fix was to check if the rv was under 110, if it was then set it to 110 so that twitter wouldnt serve client-web-legacy
this worked but someone was having problems (getting served client-web-legacy somehow) and this may fix that
the new solution is also dumb-ish but probably better than the other iterations i tried
it now checks if your browser version or rv is less than the current latest version as of now, if it is then it brings it up to that version, otherwise it leaves the user agent be
adding onto that i also made it show user agent in the security header generator error so that future debugging is easier

fix #850 + refine firefox client-web-legacy fix

---

_locales/en/messages.json
layouts/header/script.js
layouts/profile/style.css
layouts/settings/index.html
layouts/settings/script.js
scripts/config.js
scripts/injection.js

this pr adds a way to disable the transition property on the user page for the user's banner. i honestly don't know why it was there in the first place, but i assume some people like the "delay" effect it provides, which is why this pr doesn't remove it outright. the transition is off by default, as i personally think it looks better, but it doesn't really matter whether its on or off by default so please let me know which one you'd prefer ^-^
examples below. top video is with the option on, bottom is with it off
https://github.com/user-attachments/assets/381e5cfd-a93a-4191-8443-a21a51d572ae
https://github.com/user-attachments/assets/5f5a32a1-2430-4d0b-afb6-305ca1ea673c
thanks!

feat: add option for profile banner transition

---

layouts/profile/script.js

this pr adds a `--scroll` css variable so that users of custom css can add scroll animations (like the banner parallax), as there's no native css api for this (afaik). i'm honestly not sure if this is \*too\* much customization, let me know what you think :)

feat: scroll css variable for css theming users

---

scripts/helpers.js

DOMPurify removes the `target` attribute from links
This patch copies `target` to a dummy `data-` attribute, then sets it back
`target="_blank"` gets set here: https://github.com/dimdenGD/OldTwitter/blob/7b45404380f4b83fbdfa1cfb4986156ee333aade/scripts/helpers.js#L475
But then gets removed when purifying
Fixes #793

Preserve target=_blank attribute when purifying (fix #793)

---

layouts/profile/script.js

this PR undoes #873 in favour for a new, more dynamic and (from my testing) more performant system for allowing people with CSS access to access certain page properties. `--scroll` has been renamed to `--scroll-y`, and two new variables, `--mouse-x` and `--mouse-y` have been added. this change makes it clear for future contributors where these features can be added (at the top of `layouts/profile/script.js`).

feat: new css variable system for profile css developers

---

layouts/home/style.css

according to rotes, a regression has existed for a few years where link colours weren't showing in the home timeline the vast majority of the time. this pr fully fixes this issue :3
preview is below. the top user has a link colour defined, the bottom one doesn't.

fix: link colours not showing in timeline

---

scripts/helpers.js

Moves the retweet button slightly up to match new Twitter's behavior (so double-clicking the RT button retweets)

Shift retweet menu upwards

---

layouts/header/script.js
layouts/header/style.css
layouts/home/script.js
layouts/home/style.css
layouts/tweet/style.css
scripts/helpers.js
scripts/tweetviewer.js

this PR adds back support for legacy link colours by fetching profile data on the timeline **and caching it** in order to prevent rate limits. once a user has appeared on the timeline once, their colour (or lack thereof) is stored forever, and an XHR call will not be performed for them ever again. this works because you can't change your legacy link colour anymore.
it also increases the scroll height from the bottom required to trigger new tweets to appear. this change was done in order to mask the newfound latency in fetching user data and asynchronous extension storage reads, and fixes a bug where colours weren't fetched when the "Load more" button is clicked.

fix: link colours in timeline not showing

---

scripts/tweetviewer.js

this issue only applies to people who have community notes access, doesnt actually add support for "rate proposed community notes"
simply now checks if its actually a community note and not a rate proposed notes button

fix tweets with proposed community notes not loading

---

layouts/profile/script.js

[this profile](https://x.com/revtwt) would show "undefined" as the custom link because it hasn't been changed in years, and for some reason that makes it different
simply makes it work properly by using the other value that is there

fix additional url on abandoned profiles

---

_locales/en/messages.json
layouts/settings/index.html
scripts/helpers.js

Adds the feature described in #893.
Personally I like my filenames to be saved in a format that uses this parameter, e.g. `GTIpn2HacADAZiy_username.jpg`, so this PR allows for that as a possibility.
Note: I only added the string to `_locales/en/messages.json`, but it's missing from `id`, `zh_CN,` and `zh_TW` as I don't know those languages.

add filename to possible download templates

---

layouts/header/script.js

i figured it out
just changes keybind url from `/unfollows/followers` to `/old/unfollows/followers`

fix unfollowers keybind (g+u)

---

layouts/header/script.js

Fixed bug where some custom CSS elements were overwritten when modern UI was enabled

Prioritize custom CSS over modern UI CSS

---

pack.js
sandbox.html
scripts/twchallenge.js

Fixed two, including the one that (afaik) got the addon taken down from AMO.

Make firefox problems go away

---

scripts/helpers.js

extends the downloader template functionality to gifs, too

downloader template for gifs

---

layouts/notifications/script.js
scripts/iframeNavigation.js

this fixes #930 and fixes the window title sometimes having "(0)" at the beginning (0 notifications)
for the "Sandbox" fix, i can't Exactly figure out what is causing it but it happens because of iframe navigation setting the window title to the solver frame's title, and this only seems to happen when "about:blank" is what the iframe navigation sees as the current `window.location` (but i still have no idea why this causes the "Sandbox" bug, i don't understand any of the code i've tread in)
for the "0" fix, i just check if unreads are more than zero before setting the cosmetic stuff

fix some window title stuff ("Sandbox" and "0")

---

sandbox.html
scripts/twchallenge.js

the solver frame being set to display:none meant that animations couldn't play, meaning the animation part of generating x-client-transaction-id was always invalid ever since this was added
this also fixes #1030, which involves an endpoint that recently started requiring valid challenges

fix challenge solver (fixes #1030)

---

layouts/header/style.css

Hello!
Today I received a notification that has a single word that overflows the notification component, so I added the overflow CSS to notification-text, adding an ellipsis when a single word is bigger than the notification width

fix: add text overflow ellipsis to notification text

---

layouts/profile/script.js

This PR fixes an issue on the user's own followers page when using the filter functionality, due to what looks to be a new(?) additional rate limit handler on the user lookup endpoint imposed by X when called in quick succession.
At least for me, this is easily reproducible by calling https://api.x.com/1.1/users/lookup.json?user_id=1708130407663759360 six times in quick succession (opening in a browser logged in to X and refreshing the page works fine to test this). The first 5 requests succeed, while the 6th and all requests thereafter, until backing off for some period of time, begin to return `{"errors":[{"message":"Sorry, that page does not exist","code":34}]}` instead.
I tested with multiple increments and 60 seconds seemed to be the smallest increment that doesn't eventually fail.

Prevent rate limit when performing bulk follower lookup for filter

---

_locales/it/messages.json

Self explanatory title.
This PR adds the string "use_retweeted_id" that is missing in the italian translation.

Add "use_retweeted_id" string to the italian translation.
